services:
  api:
    build:
      context: ..
      dockerfile: api.Dockerfile.prod
    image: consentvault-api:staging
    env_file:
      - ./env/.env.staging
    environment:
      ENV: "staging"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [web]

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./env/.env.staging
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data_staging:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [web]

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [web]

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.staging.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks: [web]

volumes:
  db_data_staging:

networks:
  web:

