version: "3.9"

services:
  api:
    image: consentvault-api:prod
    build:
      context: ..
      dockerfile: api.Dockerfile.prod
    env_file:
      - ./env/.env.prod
    environment:
      ENV: "production"
    depends_on:
      - db
      - redis
    networks: [web]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: consentvault
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: consentvault
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    networks: [web]

  redis:
    image: redis:7
    networks: [web]

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks: [web]

volumes:
  db_data_prod:

networks:
  web:

